name: Daily Registry Updater
on:
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch:

concurrency:
  group: daily-registry-updater
  cancel-in-progress: false

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
	with:
	  ref: ${{ github.head_ref || github.ref_name }}

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install updater deps
        run: npm ci
        working-directory: updater

      - name: Ensure import dir
        run: mkdir -p data/tariffs/imports
        working-directory: updater

      - name: Scrape EE ETO
        run: npm run scrape:tariffs:ee:eto || true
        working-directory: updater

      - name: Scrape LT Žaliasis taškas
        run: npm run scrape:tariffs:lt:zaliasis || true
        working-directory: updater

      - name: Scrape LT Gamtos ateitis
        run: npm run scrape:tariffs:lt:gamtos || true
        working-directory: updater

      - name: Merge tariff imports
        run: npm run tariffs:merge
        working-directory: updater

      - name: Debug: show main.mjs and sources
        run: |
          echo "--- main.mjs head ---"
    	  sed -n '1,80p' src/main.mjs
    	  echo "--- sources dir ---"
    	  ls -la src/sources
  	working-directory: updater

      - name: Run main updater (DB upserts)
        run: npm run start
        working-directory: updater
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE: ${{ secrets.SUPABASE_SERVICE_ROLE }}

      - name: Export & upload registry.json (and tariffs)
        run: npm run export-json
        working-directory: updater
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE: ${{ secrets.SUPABASE_SERVICE_ROLE }}
