name: Daily Registry Updater
on:
  schedule:
    - cron: '7 4 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref || github.ref_name }}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - name: Install updater deps
        run: npm ci
        working-directory: updater

      - name: Merge umbrella + official sources
        run: |
          npm run update:proe:members || true
          npm run expra:members || true
          npm run sources:merge || true
        working-directory: updater
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE: ${{ secrets.SUPABASE_SERVICE_ROLE }}

      - name: Run main updater (DB upserts)
        run: npm run start
        working-directory: updater
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE: ${{ secrets.SUPABASE_SERVICE_ROLE }}

      - name: Export (deduped) to Supabase Storage
        run: |
          if [ -f src/export_deduped.mjs ]; then npm run export-json-deduped; else npm run export-json; fi
        working-directory: updater
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE: ${{ secrets.SUPABASE_SERVICE_ROLE }}